### ISSUE TITLE
Decide on how to run files

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Firmware#42]
One file can run another file either by doing:
 - `execfile("new_file.py")`
 - `__import__("new_file.py")`
 - `m = __import__("new_file.py"); m.main()`

The issues with each idea is:
 - Bit horrible, the called function can access any variables created by the parent. Upon exiting the called file, the variables created by the called function still exist
 - Need to up-import, otherwise the code can only be run once
 - Requires each file to have a main(): function

**Comment by marekventur** [comment]
I'm for option 1 or 2. Leakage or the fact that it only works once isn't that problematic when we do a softreset afterwards. I still prefer that, mostly because a badly written app can't mess up another one. 

Option 3 means we have to explain to everyone that they have to use the "def main()" wrap (and we have to make sure they removed the "main()" they've used for testing when we approve an app). It's just another thing that we have to explain in the "how to write your first app" tutorial and I'd rather avoid that.

**Comment by mattbrejza** [comment]
The reset after leaving an app seems to work OK. Ive now got it such that it wont show the splash screen on a such a reset. 

It appears the wifi remains connected, although the driver doesn't seem to expect this and gets upset.

For some reason the green led flashes 5 times on reset - dunno why, it appears to slow down the reset though

**Comment by thinkl33t** [comment]
This has been decided already.  We are using `mod = __import__(app_to_load[:-3])`. See https://github.com/emfcamp/Mk3-Firmware/blob/master/apps/home/file_loader.py#L173 for more details
